use std::env;
use std::fs;
use std::io::Write;
use std::path::PathBuf;

fn main() {
    let out_dir = PathBuf::from(env::var("OUT_DIR").unwrap());
    let sql_dir = PathBuf::from("tests/sql");

    // Tell Cargo to re-run if the SQL directory changes
    println!("cargo:rerun-if-changed=tests/sql");

    // Discover all .sql files
    let mut sql_files = Vec::new();
    if let Ok(entries) = fs::read_dir(&sql_dir) {
        for entry in entries {
            if let Ok(entry) = entry {
                let path = entry.path();
                if path.extension().and_then(|s| s.to_str()) == Some("sql") {
                    if let Some(stem) = path.file_stem().and_then(|s| s.to_str()) {
                        sql_files.push(stem.to_string());
                    }
                }
            }
        }
    }

    // Sort for deterministic order
    sql_files.sort();

    // Generate test file
    let dest_path = out_dir.join("generated_sql_tests.rs");
    let mut f = fs::File::create(&dest_path).unwrap();

    // Write imports and helper function
    writeln!(f, "// Auto-generated SQL tests - DO NOT EDIT").unwrap();
    writeln!(f, "// Generated by build.rs from tests/sql/*.sql").unwrap();
    writeln!(f).unwrap();
    writeln!(f, "use database::testing::sql_runner::run_sql_test;").unwrap();
    writeln!(f).unwrap();

    // Generate one test function per SQL file
    for file_stem in &sql_files {
        let test_name = format!("test_sql_{}", file_stem);
        writeln!(f, "#[test]").unwrap();
        writeln!(f, "fn {}() {{", test_name).unwrap();
        writeln!(
            f,
            "    run_sql_test(\"{}\", false);  // false = normal test mode",
            file_stem
        )
        .unwrap();
        writeln!(f, "}}").unwrap();
        writeln!(f).unwrap();
    }
}
