[workspace]
members = [".", "crates/database-cli"]
resolver = "2"

[package]
name = "database"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
ciborium = { version = "0.2", default-features = false, features = ["std"] }
colored = "2"
probe = "0.5"
serde = { version = "1.0.158", features = ["derive"] }
serde_bytes = "0.11"
tempfile = "3.24.0"

[dev-dependencies]
proptest = "1.1.0"
rand = "0.8.5"

[profile.release]
debug = 1
