Output doc/screenshots/repl-debug.gif

Set FontSize 14
Set Width 900
Set Height 400
Set Theme "Catppuccin Mocha"
Env PATH "/home/james/gits/database/.bin:/usr/local/sbin:/usr/local/bin:/usr/sbin:/usr/bin:/sbin:/bin"

Sleep 500ms
Type "rm test.db"
Sleep 500ms
Enter
Sleep 500ms
Type "db"
Sleep 1s
Type " test "
Backspace
Type ".db"
Sleep 3s
Type " "
Sleep 2s
Type "file"
Sleep 500ms
Type " "
Sleep 500ms
Type "tests/"
Sleep 1s
Type "sq"
Tab
Sleep 5s
Type "/inn"
Tab
Sleep 500ms
Enter
Sleep 2.5s
Type "db "
Sleep 500ms
Type " test.db"
Enter
Sleep 2.5s
Type "enter engine"
Enter
Sleep 2s
Ctrl+R
Type "comp"
Sleep 500ms
Enter
Type "debug"
Enter
Sleep 1s
Type "                                                                  "
Sleep 500ms
Type "rrrr"
Sleep 2.5s
Type "R"
Sleep 1.5s
Type "                                                                                                                                                                                                                                                      "
Sleep 500ms
Type "q"
Sleep 1s
Ctrl+D
Sleep 500ms
Ctrl+D

