// Auto-generated SQL integration tests
// Tests are generated by build.rs from tests/sql/*.sql files

// Include auto-generated tests from build.rs
include!(concat!(env!("OUT_DIR"), "/generated_sql_tests.rs"));
