CREATE TABLE t (id INTEGER, name TEXT, age INTEGER)
INSERT INTO t VALUES (1, 'Alice', 30)
INSERT INTO t VALUES (2, NULL, 25)
INSERT INTO t VALUES (3, 'Charlie', NULL)
INSERT INTO t VALUES (4, NULL, NULL)
SELECT id FROM t WHERE name IS NULL
SELECT id FROM t WHERE name IS NOT NULL
SELECT id FROM t WHERE age IS NULL
SELECT id FROM t WHERE age IS NOT NULL
SELECT id FROM t WHERE name IS NULL AND age IS NOT NULL
